<?php

namespace ContainerYtaFXth;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoGerantRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CoGerantRepository' shared autowired service.
     *
     * @return \App\Repository\CoGerantRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CoGerantRepository'] = new \App\Repository\CoGerantRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
