<?php

namespace ContainerYtaFXth;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExcerciceTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ExcerciceType' shared autowired service.
     *
     * @return \App\Form\ExcerciceType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ExcerciceType'] = new \App\Form\ExcerciceType();
    }
}
