<?php

namespace ContainerYtaFXth;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestesRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\TestesRepository' shared autowired service.
     *
     * @return \App\Repository\TestesRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\TestesRepository'] = new \App\Repository\TestesRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
