<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'dossiers' => [[], ['_controller' => 'App\\Controller\\DossierController::show'], [], [['text', '/dossier']], [], [], []],
    'dossier' => [['type'], ['_controller' => 'App\\Controller\\DossierController::index'], [], [['variable', '/', '[^/]++', 'type', true], ['text', '/dossier']], [], [], []],
    'ouvertureDossier' => [[], ['_controller' => 'App\\Controller\\DossierController::ouvertureDossier'], [], [['text', '/ouvertureDossier']], [], [], []],
    'ouvertureExcercice' => [[], ['_controller' => 'App\\Controller\\DossierController::ouvertureExcerice'], [], [['text', '/ouvertureExcercice']], [], [], []],
    'donneesExcerice' => [[], ['_controller' => 'App\\Controller\\DossierController::donneesExcerice'], [], [['text', '/donneesExcerice']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/login']], [], [], []],
    'registre' => [[], ['_controller' => 'App\\Controller\\LoginController::registre'], [], [['text', '/registre']], [], [], []],
    'confirmation' => [[], ['_controller' => 'App\\Controller\\LoginController::confirmation'], [], [['text', '/confirmation']], [], [], []],
    'definitionPaiement' => [[], ['_controller' => 'App\\Controller\\LoginController::definitionPaiement'], [], [['text', '/definitionPaiement']], [], [], []],
    'email' => [[], ['_controller' => 'App\\Controller\\LoginController::envoieMailAcceptation'], [], [['text', '/mail']], [], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\LoginController::logout'], [], [['text', '/logout']], [], [], []],
];
