<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'dossiers' => [[], ['_controller' => 'App\\Controller\\DossierController::show'], [], [['text', '/dossier']], [], [], []],
    'dossier' => [['type'], ['_controller' => 'App\\Controller\\DossierController::index'], [], [['variable', '/', '[^/]++', 'type', true], ['text', '/dossier']], [], [], []],
    'ouvertureDossier' => [[], ['_controller' => 'App\\Controller\\DossierController::ouvertureDossier'], [], [['text', '/ouvertureDossier']], [], [], []],
    'ouvertureExcercice' => [[], ['_controller' => 'App\\Controller\\DossierController::ouvertureExcerice'], [], [['text', '/ouvertureExcercice']], [], [], []],
    'donneesExcerice' => [[], ['_controller' => 'App\\Controller\\DossierController::donneesExcerice'], [], [['text', '/donneesExcerice']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/login']], [], [], []],
    'registre' => [[], ['_controller' => 'App\\Controller\\LoginController::registre'], [], [['text', '/registre']], [], [], []],
    'confirmation' => [[], ['_controller' => 'App\\Controller\\LoginController::confirmation'], [], [['text', '/confirmation']], [], [], []],
    'definitionPaiement' => [[], ['_controller' => 'App\\Controller\\LoginController::definitionPaiement'], [], [['text', '/definitionPaiement']], [], [], []],
    'email' => [[], ['_controller' => 'App\\Controller\\LoginController::envoieMailAcceptation'], [], [['text', '/mail']], [], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\LoginController::logout'], [], [['text', '/logout']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
