<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Dossier extends \App\Entity\Dossier implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'nomDossier', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'raisonSociale', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'formeJuridique', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'capitalSocial', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'nbAssocies', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'adressSiegeSocial', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'codePostale', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'numeroTel', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'adressMail', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'siret', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'franchiseEnBaseTva', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'numeroTVAintracommunaitre', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'typeImposition', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'regimeMicro', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'categorieImposition', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'regimeIndependants', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'nomGerant', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'prenomGerant', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'coGerant', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'secteurActivite', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'capital', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'nomPresident', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'prenomPresident', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'capitalPresident', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'nomEntrepreneur', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'prenomEntrepreneur', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'capitalEntrepreneur'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'nomDossier', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'raisonSociale', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'formeJuridique', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'capitalSocial', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'nbAssocies', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'adressSiegeSocial', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'codePostale', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'numeroTel', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'adressMail', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'siret', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'franchiseEnBaseTva', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'numeroTVAintracommunaitre', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'typeImposition', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'regimeMicro', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'categorieImposition', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'regimeIndependants', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'nomGerant', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'prenomGerant', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'coGerant', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'secteurActivite', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'capital', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'nomPresident', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'prenomPresident', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'capitalPresident', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'nomEntrepreneur', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'prenomEntrepreneur', '' . "\0" . 'App\\Entity\\Dossier' . "\0" . 'capitalEntrepreneur'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Dossier $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomDossier(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomDossier', []);

        return parent::getNomDossier();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomDossier(string $nomDossier): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomDossier', [$nomDossier]);

        return parent::setNomDossier($nomDossier);
    }

    /**
     * {@inheritDoc}
     */
    public function getRaisonSociale(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRaisonSociale', []);

        return parent::getRaisonSociale();
    }

    /**
     * {@inheritDoc}
     */
    public function setRaisonSociale(string $raisonSociale): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRaisonSociale', [$raisonSociale]);

        return parent::setRaisonSociale($raisonSociale);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormeJuridique(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormeJuridique', []);

        return parent::getFormeJuridique();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormeJuridique(string $formeJuridique): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormeJuridique', [$formeJuridique]);

        return parent::setFormeJuridique($formeJuridique);
    }

    /**
     * {@inheritDoc}
     */
    public function getCapitalSocial(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapitalSocial', []);

        return parent::getCapitalSocial();
    }

    /**
     * {@inheritDoc}
     */
    public function setCapitalSocial(string $capitalSocial): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCapitalSocial', [$capitalSocial]);

        return parent::setCapitalSocial($capitalSocial);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbAssocies(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbAssocies', []);

        return parent::getNbAssocies();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbAssocies(string $nbAssocies): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbAssocies', [$nbAssocies]);

        return parent::setNbAssocies($nbAssocies);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdressSiegeSocial(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdressSiegeSocial', []);

        return parent::getAdressSiegeSocial();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdressSiegeSocial(string $adressSiegeSocial): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdressSiegeSocial', [$adressSiegeSocial]);

        return parent::setAdressSiegeSocial($adressSiegeSocial);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostale(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostale', []);

        return parent::getCodePostale();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostale(string $codePostale): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostale', [$codePostale]);

        return parent::setCodePostale($codePostale);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', []);

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille(string $ville): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', [$ville]);

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroTel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroTel', []);

        return parent::getNumeroTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroTel(string $numeroTel): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroTel', [$numeroTel]);

        return parent::setNumeroTel($numeroTel);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdressMail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdressMail', []);

        return parent::getAdressMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdressMail(string $adressMail): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdressMail', [$adressMail]);

        return parent::setAdressMail($adressMail);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiret(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiret', []);

        return parent::getSiret();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiret(string $siret): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiret', [$siret]);

        return parent::setSiret($siret);
    }

    /**
     * {@inheritDoc}
     */
    public function getFranchiseEnBaseTva(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFranchiseEnBaseTva', []);

        return parent::getFranchiseEnBaseTva();
    }

    /**
     * {@inheritDoc}
     */
    public function setFranchiseEnBaseTva(string $franchiseEnBaseTva): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFranchiseEnBaseTva', [$franchiseEnBaseTva]);

        return parent::setFranchiseEnBaseTva($franchiseEnBaseTva);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroTVAintracommunaitre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroTVAintracommunaitre', []);

        return parent::getNumeroTVAintracommunaitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroTVAintracommunaitre(?string $numeroTVAintracommunaitre): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroTVAintracommunaitre', [$numeroTVAintracommunaitre]);

        return parent::setNumeroTVAintracommunaitre($numeroTVAintracommunaitre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeImposition(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeImposition', []);

        return parent::getTypeImposition();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeImposition(string $typeImposition): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeImposition', [$typeImposition]);

        return parent::setTypeImposition($typeImposition);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegimeMicro(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegimeMicro', []);

        return parent::getRegimeMicro();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegimeMicro(string $regimeMicro): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegimeMicro', [$regimeMicro]);

        return parent::setRegimeMicro($regimeMicro);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorieImposition(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorieImposition', []);

        return parent::getCategorieImposition();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorieImposition(string $categorieImposition): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorieImposition', [$categorieImposition]);

        return parent::setCategorieImposition($categorieImposition);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegimeIndependants(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegimeIndependants', []);

        return parent::getRegimeIndependants();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegimeIndependants(string $regimeIndependants): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegimeIndependants', [$regimeIndependants]);

        return parent::setRegimeIndependants($regimeIndependants);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomGerant(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomGerant', []);

        return parent::getNomGerant();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomGerant(string $nomGerant): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomGerant', [$nomGerant]);

        return parent::setNomGerant($nomGerant);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomGerant(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomGerant', []);

        return parent::getPrenomGerant();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomGerant(string $prenomGerant): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomGerant', [$prenomGerant]);

        return parent::setPrenomGerant($prenomGerant);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoGerant(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoGerant', []);

        return parent::getCoGerant();
    }

    /**
     * {@inheritDoc}
     */
    public function addCoGerant(\App\Entity\coGerant $coGerant): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCoGerant', [$coGerant]);

        return parent::addCoGerant($coGerant);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCoGerant(\App\Entity\coGerant $coGerant): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCoGerant', [$coGerant]);

        return parent::removeCoGerant($coGerant);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $user): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecteurActivite(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecteurActivite', []);

        return parent::getSecteurActivite();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecteurActivite(string $secteurActivite): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecteurActivite', [$secteurActivite]);

        return parent::setSecteurActivite($secteurActivite);
    }

    /**
     * {@inheritDoc}
     */
    public function getCapital(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapital', []);

        return parent::getCapital();
    }

    /**
     * {@inheritDoc}
     */
    public function setCapital(?float $capital): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCapital', [$capital]);

        return parent::setCapital($capital);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomPresident(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomPresident', []);

        return parent::getNomPresident();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomPresident(?string $nomPresident): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomPresident', [$nomPresident]);

        return parent::setNomPresident($nomPresident);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomPresident(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomPresident', []);

        return parent::getPrenomPresident();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomPresident(?string $prenomPresident): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomPresident', [$prenomPresident]);

        return parent::setPrenomPresident($prenomPresident);
    }

    /**
     * {@inheritDoc}
     */
    public function getCapitalPresident(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapitalPresident', []);

        return parent::getCapitalPresident();
    }

    /**
     * {@inheritDoc}
     */
    public function setCapitalPresident(?float $capitalPresident): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCapitalPresident', [$capitalPresident]);

        return parent::setCapitalPresident($capitalPresident);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomEntrepreneur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomEntrepreneur', []);

        return parent::getNomEntrepreneur();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomEntrepreneur(?string $nomEntrepreneur): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomEntrepreneur', [$nomEntrepreneur]);

        return parent::setNomEntrepreneur($nomEntrepreneur);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomEntrepreneur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomEntrepreneur', []);

        return parent::getPrenomEntrepreneur();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomEntrepreneur(?string $prenomEntrepreneur): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomEntrepreneur', [$prenomEntrepreneur]);

        return parent::setPrenomEntrepreneur($prenomEntrepreneur);
    }

    /**
     * {@inheritDoc}
     */
    public function getCapitalEntrepreneur(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapitalEntrepreneur', []);

        return parent::getCapitalEntrepreneur();
    }

    /**
     * {@inheritDoc}
     */
    public function setCapitalEntrepreneur(?float $capitalEntrepreneur): \App\Entity\Dossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCapitalEntrepreneur', [$capitalEntrepreneur]);

        return parent::setCapitalEntrepreneur($capitalEntrepreneur);
    }

}
